const defaultTransform = () => ({
  x: 0,
  y: 0,
  width: 100,
  height: 100,
  rotation: 0,
});
export const BaseComponents = [
  {
    icon: 'text',
    name: '文本',
    type: 'text',
    height: 28,
    width: 100,
  },
  {
    icon: 'anniu1',
    name: '按钮',
    type: 'button',
    height: 32,
    width: 100,
  },
  {
    icon: 'juxing',
    name: '矩形',
    type: 'rect',
    width: 100,
    height: 100,
  },
  {
    icon: 'Triangle',
    name: '三角形',
    type: 'triangle',
    width: 100,
    height: 100,
  },
  {
    icon: 'qipao',
    name: '气泡',
    type: 'bubble',
    width: 300,
    height: 100,
  },
  {
    icon: 'xianduanceliang',
    name: '直线',
    type: 'line',
    width: 200,
    height: 1,
  },
  {
    icon: 'icon_yuanxing',
    name: '圆',
    type: 'circle',
    width: 150,
    height: 150,
  },
  {
    icon: 'danhangshuru',
    name: '单行输入',
    type: 'input',
    width: 180,
    height: 28,
  },
  {
    icon: 'fuhao-duohangshurukuang',
    name: '多行输入',
    type: 'textarea',
    width: 200,
    height: 100,
  },
  {
    icon: 'xialaxuanze',
    name: '下拉选择',
    type: 'select',
    height: 28,
    width: 180,
  },
  {
    icon: 'radio',
    name: '单选',
    type: 'radio',
    height: 66,
    width: 180,
  },
  {
    icon: 'checkboxlist',
    name: '多选',
    type: 'checkbox',
    height: 66,
    width: 180,
  },
  {
    icon: 'tupian-copy-copy',
    name: '图片',
    type: 'image',
    height: 80,
    width: 80,
  },
  {
    // iconfont 无表格字形，用自绘 SVG（Icon 组件 svg: 前缀）：外框 + 表头横线 + 纵向分列线
    icon: 'svg:<rect x="3" y="3" width="18" height="18" rx="2"/><path d="M3 9h18M3 15h18M9 3v18"/>',
    name: '表格',
    type: 'table',
    width: 400,
    height: 200,
  },
];
export const ComponentIconMap = {
  select: 'xialaxuanze',
  radio: 'radio',
  checkbox: 'checkboxlist',
  textarea: 'fuhao-duohangshurukuang',
  input: 'danhangshuru',
  circle: 'icon_yuanxing',
  line: 'xianduanceliang',
  bubble: 'qipao',
  text: 'text',
  image: 'tupian-copy-copy',
  button: 'anniu1',
  triangle: 'Triangle',
  rect: 'juxing',
  icon: 'tubiao',
  block: 'group',
  table: 'table',
};
