let PREVIEW_URL, COMMUNITY_URL, COMMUNITY_TUTORIAL, BASE_OSS

BASE_OSS = 'https://zuimeiaj.oss-cn-shenzhen.aliyuncs.com/'
PREVIEW_URL = 'http://localhost:3002/'
COMMUNITY_URL = 'http://39.98.82.227:8080/'
COMMUNITY_TUTORIAL = 'http://39.98.82.227:8080/yoyoo'

export {PREVIEW_URL, COMMUNITY_TUTORIAL, COMMUNITY_URL, BASE_OSS};