export const PresetIcons = {
  'icon-biaodan': {
    items: [
      { data: 'icon-biaodan_check_box', fontContent: 'e82d', type: 'icon', name: 'check_box' },
      { data: 'icon-biaodan_qipao1', fontContent: 'e82c', type: 'icon', name: '气泡' },
      { data: 'icon-biaodan_qipao', fontContent: 'e82b', type: 'icon', name: '气泡' },
      { data: 'icon-biaodan_moban', fontContent: 'e82a', type: 'icon', name: '地址' },
      { data: 'icon-biaodan_help', fontContent: 'e829', type: 'icon', name: 'help' },
      { data: 'icon-biaodan_faq', fontContent: 'e828', type: 'icon', name: '气泡' },
      { data: 'icon-biaodan_help2', fontContent: 'e827', type: 'icon', name: 'help' },
      { data: 'icon-biaodan_address', fontContent: 'e826', type: 'icon', name: '地址' },
      { data: 'icon-biaodan_mima2', fontContent: 'e825', type: 'icon', name: '密码' },
      { data: 'icon-biaodan_youxiang1', fontContent: 'e824', type: 'icon', name: '邮箱' },
      { data: 'icon-biaodan_youxiang', fontContent: 'e823', type: 'icon', name: '邮箱' },
      { data: 'icon-biaodan_shouji1', fontContent: 'e822', type: 'icon', name: '手机' },
      { data: 'icon-biaodan_yonghu2', fontContent: 'e821', type: 'icon', name: '用户' },
      { data: 'icon-biaodan_mima1', fontContent: 'e820', type: 'icon', name: '密码' },
      { data: 'icon-biaodan_verification-jf', fontContent: 'e81f', type: 'icon', name: '验证码' },
      { data: 'icon-biaodan_xingtaiduICON-', fontContent: 'e81e', type: 'icon', name: '验证码' },
      { data: 'icon-biaodan_yonghu1', fontContent: 'e81d', type: 'icon', name: '用户' },
      { data: 'icon-biaodan_shouji', fontContent: 'e81c', type: 'icon', name: '手机' },
      { data: 'icon-biaodan_mima', fontContent: 'e81b', type: 'icon', name: '密码' },
      { data: 'icon-biaodan_yonghu', fontContent: 'e81a', type: 'icon', name: '用户' },
      { data: 'icon-biaodan_sousuo1', fontContent: 'e819', type: 'icon', name: '搜索' },
      { data: 'icon-biaodan_sousuo', fontContent: 'e818', type: 'icon', name: '搜索' },
      { data: 'icon-biaodan_yanzhengma', fontContent: 'e817', type: 'icon', name: '验证码' },
      { data: 'icon-biaodan_radiono', fontContent: 'e816', type: 'icon', name: 'radiono' },
      { data: 'icon-biaodan_SliderOff', fontContent: 'e815', type: 'icon', name: 'Slider Off' },
      { data: 'icon-biaodan_jinggao', fontContent: 'e814', type: 'icon', name: 'warning ' },
      { data: 'icon-biaodan_info', fontContent: 'e813', type: 'icon', name: 'info' },
      { data: 'icon-biaodan_pwd', fontContent: 'e812', type: 'icon', name: 'pwd' },
      { data: 'icon-biaodan_tixingx', fontContent: 'e811', type: 'icon', name: 'warning' },
      { data: 'icon-biaodan_icon02', fontContent: 'e810', type: 'icon', name: '添加' },
      { data: 'icon-biaodan_shangchuan', fontContent: 'e80f', type: 'icon', name: '上传' },
      { data: 'icon-biaodan_tmp-illegal', fontContent: 'e80e', type: 'icon', name: 'error' },
      { data: 'icon-biaodan_xiazai-', fontContent: 'e80d', type: 'icon', name: '下载' },
      { data: 'icon-biaodan_error1', fontContent: 'e80c', type: 'icon', name: 'error' },
      { data: 'icon-biaodan_danxuanxuanzhong16', fontContent: 'e80b', type: 'icon', name: '单选选中_16' },
      { data: 'icon-biaodan_icon-el-date-picker', fontContent: 'e80a', type: 'icon', name: 'date-picker' },
      { data: 'icon-biaodan_success1', fontContent: 'e809', type: 'icon', name: 'success' },
      { data: 'icon-biaodan_minus', fontContent: 'e808', type: 'icon', name: 'min' },
      { data: 'icon-biaodan_error', fontContent: 'e807', type: 'icon', name: 'error' },
      { data: 'icon-biaodan_xiazai', fontContent: 'e806', type: 'icon', name: '下载' },
      { data: 'icon-biaodan_quesition-circle', fontContent: 'e805', type: 'icon', name: 'quesition-circle' },
      { data: 'icon-biaodan_quesition', fontContent: 'e804', type: 'icon', name: 'quesition' },
      { data: 'icon-biaodan_xuanze', fontContent: 'e802', type: 'icon', name: '多选项' },
      { data: 'icon-biaodan_duoxuan', fontContent: 'e801', type: 'icon', name: '多选' },
      { data: 'icon-biaodan_success', fontContent: 'e803', type: 'icon', name: 'success' },
      { data: 'icon-biaodan_min', fontContent: 'e800', type: 'icon', name: 'min' },
      { data: 'icon-biaodan_upload', fontContent: 'e7ff', type: 'icon', name: '上传' },
      { data: 'icon-biaodan_SliderOn', fontContent: 'e7fe', type: 'icon', name: 'Slider On' },
      { data: 'icon-biaodan_iconfontoptionbutton', fontContent: 'e7fd', type: 'icon', name: '单选' },
    ],
    name: '表单',
  },
  'icon-wuliu': {
    items: [
      { data: 'icon-wuliu_bianji', fontContent: 'e7fc', type: 'icon', name: '编辑' },
      { data: 'icon-wuliu_quyuguanli', fontContent: 'e7fb', type: 'icon', name: '区域管理' },
      { data: 'icon-wuliu_woderenwu', fontContent: 'e7fa', type: 'icon', name: '我的任务' },
      { data: 'icon-wuliu_jiluziliaoguanli', fontContent: 'e7f9', type: 'icon', name: '记录资料' },
      { data: 'icon-wuliu_kongzhitai_', fontContent: 'e7f8', type: 'icon', name: '控制台' },
      { data: 'icon-wuliu_shanchu', fontContent: 'e7f7', type: 'icon', name: '删除' },
      { data: 'icon-wuliu_xiangmu1', fontContent: 'e7f6', type: 'icon', name: '项目' },
      { data: 'icon-wuliu_bumen', fontContent: 'e7f5', type: 'icon', name: '部门' },
      { data: 'icon-wuliu_shizhong', fontContent: 'e7f4', type: 'icon', name: '时钟' },
      { data: 'icon-wuliu_yijianfankui1', fontContent: 'e7f3', type: 'icon', name: '意见反馈' },
      { data: 'icon-wuliu_gerenxinxi', fontContent: 'e7f2', type: 'icon', name: '个人信息' },
      { data: 'icon-wuliu_tongji', fontContent: 'e7f1', type: 'icon', name: '统计' },
      { data: 'icon-wuliu_renwu_', fontContent: 'e7f0', type: 'icon', name: '任务_1' },
      { data: 'icon-wuliu_biaoqian', fontContent: 'e7ef', type: 'icon', name: '标签' },
      { data: 'icon-wuliu_zuzhijigou', fontContent: 'e7ee', type: 'icon', name: '组织机构' },
      { data: 'icon-wuliu_yuyin', fontContent: 'e7ed', type: 'icon', name: '语音' },
      { data: 'icon-wuliu_yunpeiguanli', fontContent: 'e7ec', type: 'icon', name: '运配管理' },
      { data: 'icon-wuliu_xiugaimima', fontContent: 'e7eb', type: 'icon', name: '修改密码' },
      { data: 'icon-wuliu_yijianfankui', fontContent: 'e7ea', type: 'icon', name: '意见反馈' },
      { data: 'icon-wuliu_yonghuguanli', fontContent: 'e7e9', type: 'icon', name: '用户管理' },
      { data: 'icon-wuliu_xiaoxitongzhi', fontContent: 'e7e8', type: 'icon', name: '消息通知' },
      { data: 'icon-wuliu_tuichu', fontContent: 'e7e7', type: 'icon', name: '退出' },
      { data: 'icon-wuliu_tiaoduguanli', fontContent: 'e7e6', type: 'icon', name: '调度管理' },
      { data: 'icon-wuliu_wancheng', fontContent: 'e7e5', type: 'icon', name: '完成' },
      { data: 'icon-wuliu_sousuo', fontContent: 'e7e4', type: 'icon', name: '搜索' },
      { data: 'icon-wuliu_shouye', fontContent: 'e7e3', type: 'icon', name: '首页' },
      { data: 'icon-wuliu_tianjia', fontContent: 'e7e2', type: 'icon', name: '添加' },
      { data: 'icon-wuliu_shezhi', fontContent: 'e7e1', type: 'icon', name: '设置' },
      { data: 'icon-wuliu_shouru1', fontContent: 'e7e0', type: 'icon', name: '收入' },
      { data: 'icon-wuliu_qitaxiaoxi', fontContent: 'e7df', type: 'icon', name: '其他消息' },
      { data: 'icon-wuliu_saoyisao', fontContent: 'e7de', type: 'icon', name: '扫一扫' },
      { data: 'icon-wuliu_shanguangdeng', fontContent: 'e7dd', type: 'icon', name: '闪光灯' },
      { data: 'icon-wuliu_mima', fontContent: 'e7dc', type: 'icon', name: '密码' },
      { data: 'icon-wuliu_jiaoyitixing', fontContent: 'e7db', type: 'icon', name: '交易提醒' },
      { data: 'icon-wuliu_kongzhitai', fontContent: 'e7da', type: 'icon', name: '控制台' },
      { data: 'icon-wuliu_jixiaokaohe', fontContent: 'e7d9', type: 'icon', name: '绩效考核' },
      { data: 'icon-wuliu_fukuan', fontContent: 'e7d8', type: 'icon', name: '付款' },
      { data: 'icon-wuliu_gerenzhongxin', fontContent: 'e7d7', type: 'icon', name: '个人中心' },
      { data: 'icon-wuliu_gongzuotai', fontContent: 'e7d6', type: 'icon', name: '工作台' },
      { data: 'icon-wuliu_fahuo', fontContent: 'e7d5', type: 'icon', name: '发货_1' },
      { data: 'icon-wuliu_fachejihua', fontContent: 'e7d4', type: 'icon', name: '发车计划' },
      { data: 'icon-wuliu_feiyongchaxun', fontContent: 'e7d3', type: 'icon', name: '费用查询' },
      { data: 'icon-wuliu_erweima', fontContent: 'e7d2', type: 'icon', name: '二维码' },
      { data: 'icon-wuliu_dingdanguanli', fontContent: 'e7d1', type: 'icon', name: '订单管理' },
      { data: 'icon-wuliu_phone_1', fontContent: 'e7d0', type: 'icon', name: '电话_1' },
      { data: 'icon-wuliu_dailishang', fontContent: 'e7cf', type: 'icon', name: '代理商' },
      { data: 'icon-wuliu_cheliangguanli', fontContent: 'e7ce', type: 'icon', name: '车辆管理' },
      { data: 'icon-wuliu_dituweizhi', fontContent: 'e7cd', type: 'icon', name: '地图位置' },
      { data: 'icon-wuliu_chakan', fontContent: 'e7cc', type: 'icon', name: '查看' },
      { data: 'icon-wuliu_phone', fontContent: 'e7cb', type: 'icon', name: '电话' },
      { data: 'icon-wuliu_xiangmu', fontContent: 'e7ca', type: 'icon', name: '项目' },
      { data: 'icon-wuliu_bumenguanli', fontContent: 'e7c9', type: 'icon', name: '部门管理' },
      { data: 'icon-wuliu_bianji-', fontContent: 'e7c8', type: 'icon', name: '编辑_1' },
      { data: 'icon-wuliu_menu-', fontContent: 'e7c7', type: 'icon', name: 'menu_2' },
      { data: 'icon-wuliu_single-arrow', fontContent: 'e7c6', type: 'icon', name: '单箭头' },
      { data: 'icon-wuliu_train1', fontContent: 'e7c5', type: 'icon', name: 'train' },
      { data: 'icon-wuliu_change-password', fontContent: 'e7c4', type: 'icon', name: '修改密码' },
      { data: 'icon-wuliu_menu1', fontContent: 'e7c3', type: 'icon', name: '菜单' },
      { data: 'icon-wuliu_train', fontContent: 'e7c2', type: 'icon', name: 'train' },
      { data: 'icon-wuliu_service-point', fontContent: 'e7c1', type: 'icon', name: 'service' },
      { data: 'icon-wuliu_payment', fontContent: 'e7c0', type: 'icon', name: 'payment' },
      { data: 'icon-wuliu_menu', fontContent: 'e7bf', type: 'icon', name: 'menu' },
      { data: 'icon-wuliu_infor', fontContent: 'e7be', type: 'icon', name: 'infor' },
      { data: 'icon-wuliu_notice', fontContent: 'e7bd', type: 'icon', name: '通知_' },
      { data: 'icon-wuliu_image', fontContent: 'e7bc', type: 'icon', name: '图片' },
      { data: 'icon-wuliu_cash-payment', fontContent: 'e7bb', type: 'icon', name: '现金支付' },
      { data: 'icon-wuliu_shouru', fontContent: 'e7ba', type: 'icon', name: '收入' },
      { data: 'icon-wuliu_goods', fontContent: 'e7b9', type: 'icon', name: '商品管理' },
      { data: 'icon-wuliu_Ship', fontContent: 'e7b8', type: 'icon', name: '发货' },
      { data: 'icon-wuliu_Crate', fontContent: 'e7b7', type: 'icon', name: '周转箱' },
      { data: 'icon-wuliu_Site', fontContent: 'e7b6', type: 'icon', name: '站点线路' },
      { data: 'icon-wuliu_driver', fontContent: 'e7b5', type: 'icon', name: '司机' },
      { data: 'icon-wuliu_gongyingshang', fontContent: 'e7b4', type: 'icon', name: '供应商' },
      { data: 'icon-wuliu_truck', fontContent: 'e7b3', type: 'icon', name: '车辆' },
      { data: 'icon-wuliu_position', fontContent: 'e7b2', type: 'icon', name: '职位' },
      { data: 'icon-wuliu_edit', fontContent: 'e7b1', type: 'icon', name: '编辑' },
      { data: 'icon-wuliu_wuliupeisong-', fontContent: 'ece6', type: 'icon', name: '物流配送-1' },
      { data: 'icon-wuliu_wuliutouming', fontContent: 'e7b0', type: 'icon', name: '物流透明' },
      { data: 'icon-wuliu_paisongtixing', fontContent: 'e7af', type: 'icon', name: '派送提醒-物流详情' },
      { data: 'icon-wuliu_wwuliu-', fontContent: 'e7ae', type: 'icon', name: 'w物流-01' },
      { data: 'icon-wuliu_mn-wuliu', fontContent: 'e7ad', type: 'icon', name: 'AK-MN物流' },
      { data: 'icon-wuliu_wuliu-', fontContent: 'e7ac', type: 'icon', name: '物流-01' },
      { data: 'icon-wuliu_wuliuzhongxinziliaoshenhe', fontContent: 'e7ab', type: 'icon', name: '物流中心资料审核' },
      { data: 'icon-wuliu_wuliu3', fontContent: 'e7aa', type: 'icon', name: '物流' },
      { data: 'icon-wuliu_wuliuma', fontContent: 'e7a9', type: 'icon', name: '物流码' },
      { data: 'icon-wuliu_wuliu2', fontContent: 'e7a8', type: 'icon', name: '物流' },
      { data: 'icon-wuliu_navwuliuzhongxin', fontContent: 'e7a7', type: 'icon', name: 'nav物流中心' },
      { data: 'icon-wuliu_wuliuxinxi', fontContent: 'e7a6', type: 'icon', name: '物流信息' },
      { data: 'icon-wuliu_wuliuguanli', fontContent: 'e7a5', type: 'icon', name: '物流管理' },
      { data: 'icon-wuliu_wuliu1', fontContent: 'e7a4', type: 'icon', name: '物流' },
      { data: 'icon-wuliu_guanyuyouxinwuliu', fontContent: 'e846', type: 'icon', name: '关于优信物流' },
      { data: 'icon-wuliu_wuliu', fontContent: 'e7a3', type: 'icon', name: '物流' },
    ],
    name: '物流',
  },
  'icon-jinrong': {
    items: [
      { data: 'icon-jinrong_zizhizhengshu', fontContent: 'e7a2', type: 'icon', name: '资质证书' },
      { data: 'icon-jinrong_zhuanlixinxi', fontContent: 'e7a1', type: 'icon', name: '专利信息' },
      { data: 'icon-jinrong_zhuzuoquanxinxi', fontContent: 'e7a0', type: 'icon', name: '著作权信息' },
      { data: 'icon-jinrong_zhuyaorenyuan', fontContent: 'e79f', type: 'icon', name: '主要人员' },
      { data: 'icon-jinrong_zhaotoubiao', fontContent: 'e79e', type: 'icon', name: '招投标' },
      { data: 'icon-jinrong_zhenshixingming', fontContent: 'e79d', type: 'icon', name: '真实姓名' },
      { data: 'icon-jinrong_zhaiquanxinxi', fontContent: 'e79c', type: 'icon', name: '债券信息' },
      { data: 'icon-jinrong_yongtu', fontContent: 'e79b', type: 'icon', name: '用途' },
      { data: 'icon-jinrong_yujing', fontContent: 'e79a', type: 'icon', name: '预警' },
      { data: 'icon-jinrong_yijianfankui', fontContent: 'e799', type: 'icon', name: '意见反馈' },
      { data: 'icon-jinrong_yinhangqiahao', fontContent: 'e798', type: 'icon', name: '银行卡号' },
      { data: 'icon-jinrong_xuanze-yixuan', fontContent: 'e797', type: 'icon', name: '选择-已选' },
      { data: 'icon-jinrong_yanzhongweifan', fontContent: 'e796', type: 'icon', name: '严重违反' },
      { data: 'icon-jinrong_xinzeng', fontContent: 'e795', type: 'icon', name: '新增' },
      { data: 'icon-jinrong_xuanze-kong', fontContent: 'e794', type: 'icon', name: '选择-空' },
      { data: 'icon-jinrong_xiangmujine', fontContent: 'e793', type: 'icon', name: '项目金额' },
      { data: 'icon-jinrong_xiaoxidaiban', fontContent: 'e792', type: 'icon', name: '消息待办' },
      { data: 'icon-jinrong_xiaoqu', fontContent: 'e791', type: 'icon', name: '小区' },
      { data: 'icon-jinrong_xiangmu', fontContent: 'e790', type: 'icon', name: '项目' },
      { data: 'icon-jinrong_wode1', fontContent: 'e78f', type: 'icon', name: '我的' },
      { data: 'icon-jinrong_wangzhanxinxi', fontContent: 'e78e', type: 'icon', name: '网站信息' },
      { data: 'icon-jinrong_wangzhanbeian', fontContent: 'e78d', type: 'icon', name: '网站备案' },
      { data: 'icon-jinrong_touzishijian', fontContent: 'e78c', type: 'icon', name: '投资事件' },
      { data: 'icon-jinrong_shidagudong', fontContent: 'e78b', type: 'icon', name: '十大股东' },
      { data: 'icon-jinrong_tongji', fontContent: 'e78a', type: 'icon', name: '统计' },
      { data: 'icon-jinrong_shuiwupingji', fontContent: 'e789', type: 'icon', name: '税务评级' },
      { data: 'icon-jinrong_sousuo', fontContent: 'e788', type: 'icon', name: '搜索' },
      { data: 'icon-jinrong_shouye', fontContent: 'e787', type: 'icon', name: '首页' },
      { data: 'icon-jinrong_shoujihaoma', fontContent: 'e786', type: 'icon', name: '手机号码' },
      { data: 'icon-jinrong_shixinren', fontContent: 'e785', type: 'icon', name: '失信人' },
      { data: 'icon-jinrong_shenfenzhenghao', fontContent: 'e784', type: 'icon', name: '身份证号' },
      { data: 'icon-jinrong_shezhi', fontContent: 'e783', type: 'icon', name: '设置' },
      { data: 'icon-jinrong_shangshigonggao', fontContent: 'e782', type: 'icon', name: '上市公告' },
      { data: 'icon-jinrong_qianshuigonggao', fontContent: 'e781', type: 'icon', name: '欠税公告' },
      { data: 'icon-jinrong_shaixuan', fontContent: 'e780', type: 'icon', name: '筛选' },
      { data: 'icon-jinrong_shangbiaoxinxi', fontContent: 'e77f', type: 'icon', name: '商标信息' },
      { data: 'icon-jinrong_rongzilishi', fontContent: 'e77e', type: 'icon', name: '融资历史' },
      { data: 'icon-jinrong_richeng', fontContent: 'e77d', type: 'icon', name: '日程' },
      { data: 'icon-jinrong_qiandaozuji', fontContent: 'e77c', type: 'icon', name: '签到足迹' },
      { data: 'icon-jinrong_qianliyan', fontContent: 'e77b', type: 'icon', name: '千里眼' },
      { data: 'icon-jinrong_qiandao', fontContent: 'e77a', type: 'icon', name: '签到' },
      { data: 'icon-jinrong_qiyezhuangtai', fontContent: 'e779', type: 'icon', name: '企业状态' },
      { data: 'icon-jinrong_qiyejianjie', fontContent: 'e778', type: 'icon', name: '企业简介' },
      { data: 'icon-jinrong_qiyeyewu', fontContent: 'e777', type: 'icon', name: '企业业务' },
      { data: 'icon-jinrong_qiyexinwen', fontContent: 'e776', type: 'icon', name: '企业新闻' },
      { data: 'icon-jinrong_qiyehuaxiangchaxun', fontContent: 'e775', type: 'icon', name: '企业画像查询' },
      { data: 'icon-jinrong_pingfen-xing', fontContent: 'e774', type: 'icon', name: '评分-星' },
      { data: 'icon-jinrong_jia', fontContent: 'e773', type: 'icon', name: '加' },
      { data: 'icon-jinrong_kaitinggonggao', fontContent: 'e772', type: 'icon', name: '开庭公告' },
      { data: 'icon-jinrong_peiguqingkuang', fontContent: 'e771', type: 'icon', name: '配股情况' },
      { data: 'icon-jinrong_jingpinxinxi', fontContent: 'e770', type: 'icon', name: '竞品信息' },
      { data: 'icon-jinrong_jingyingyichang', fontContent: 'e76f', type: 'icon', name: '经营异常' },
      { data: 'icon-jinrong_jiantou', fontContent: 'e76e', type: 'icon', name: '箭头' },
      { data: 'icon-jinrong_jibenxinxi-', fontContent: 'e76d', type: 'icon', name: '基本信息-2' },
      { data: 'icon-jinrong_jibenxinxi', fontContent: 'e76c', type: 'icon', name: '基本信息' },
      { data: 'icon-jinrong_huifang', fontContent: 'e76b', type: 'icon', name: '回访' },
      { data: 'icon-jinrong_hexintuandui', fontContent: 'e76a', type: 'icon', name: '核心团队' },
      { data: 'icon-jinrong_huanbenqueren', fontContent: 'e769', type: 'icon', name: '还本确认' },
      { data: 'icon-jinrong_guquanchuzhi', fontContent: 'e768', type: 'icon', name: '股权出质' },
      { data: 'icon-jinrong_hangzhengchufa', fontContent: 'e767', type: 'icon', name: '行政处罚' },
      { data: 'icon-jinrong_hangyefenbu', fontContent: 'e766', type: 'icon', name: '行业分布' },
      { data: 'icon-jinrong_guanlianfujian', fontContent: 'e765', type: 'icon', name: '关联附件' },
      { data: 'icon-jinrong_guquanbiangeng', fontContent: 'e764', type: 'icon', name: '股权变更' },
      { data: 'icon-jinrong_gubenjiegou', fontContent: 'e763', type: 'icon', name: '股本结构' },
      { data: 'icon-jinrong_gudongxinxi', fontContent: 'e762', type: 'icon', name: '股东信息' },
      { data: 'icon-jinrong_gudongchuzi', fontContent: 'e761', type: 'icon', name: '股东出资' },
      { data: 'icon-jinrong_gerenhuaxiangchaxun', fontContent: 'e760', type: 'icon', name: '个人画像查询' },
      { data: 'icon-jinrong_goudixinxi', fontContent: 'e75f', type: 'icon', name: '购地信息' },
      { data: 'icon-jinrong_fuxiqueren', fontContent: 'e75e', type: 'icon', name: '付息确认' },
      { data: 'icon-jinrong_gongzuohuizong', fontContent: 'e75d', type: 'icon', name: '工作汇总' },
      { data: 'icon-jinrong_beizhihangren', fontContent: 'e75c', type: 'icon', name: '被执行人' },
      { data: 'icon-jinrong_gaoguanxinxi', fontContent: 'e75b', type: 'icon', name: '高管信息' },
      { data: 'icon-jinrong_falvsusong', fontContent: 'e75a', type: 'icon', name: '法律诉讼' },
      { data: 'icon-jinrong_fenhongqingkuang', fontContent: 'e759', type: 'icon', name: '分红情况' },
      { data: 'icon-jinrong_fangchanpinggu', fontContent: 'e758', type: 'icon', name: '房产评估' },
      { data: 'icon-jinrong_fenzhijigou', fontContent: 'e757', type: 'icon', name: '分支机构' },
      { data: 'icon-jinrong_fanhui', fontContent: 'e756', type: 'icon', name: '返回' },
      { data: 'icon-jinrong_fayuangonggao', fontContent: 'e755', type: 'icon', name: '法院公告' },
      { data: 'icon-jinrong_fahangxiangguan', fontContent: 'e754', type: 'icon', name: '发行相关' },
      { data: 'icon-jinrong_duiwaitouzi-', fontContent: 'e753', type: 'icon', name: '对外投资-1' },
      { data: 'icon-jinrong_duiwaitouzi', fontContent: 'e752', type: 'icon', name: '对外投资' },
      { data: 'icon-jinrong_diqufenbu', fontContent: 'e751', type: 'icon', name: '地区分布' },
      { data: 'icon-jinrong_duiwaidanbao', fontContent: 'e750', type: 'icon', name: '对外担保' },
      { data: 'icon-jinrong_dongchandiya', fontContent: 'e74f', type: 'icon', name: '动产抵押' },
      { data: 'icon-jinrong_chouchajiancha', fontContent: 'e74e', type: 'icon', name: '抽查检查' },
      { data: 'icon-jinrong_chengshi', fontContent: 'e74d', type: 'icon', name: '城市' },
      { data: 'icon-jinrong_chanpinxinxi', fontContent: 'e74c', type: 'icon', name: '产品信息' },
      { data: 'icon-jinrong_chakanqiyehuaxiang', fontContent: 'e74b', type: 'icon', name: '查看企业画像' },
      { data: 'icon-jinrong_cangukonggu', fontContent: 'e74a', type: 'icon', name: '参股控股' },
      { data: 'icon-jinrong_caiji', fontContent: 'e749', type: 'icon', name: '采集' },
      { data: 'icon-jinrong_biangengjilu', fontContent: 'e748', type: 'icon', name: '变更记录' },
      { data: 'icon-jinrong_baogao', fontContent: 'e747', type: 'icon', name: '报告' },
      { data: 'icon-jinrong_xuexi_nor', fontContent: 'e746', type: 'icon', name: '学习_nor' },
      { data: 'icon-jinrong_daohang-shouye', fontContent: 'e745', type: 'icon', name: '导航-首页' },
      { data: 'icon-jinrong_tongjitu', fontContent: 'e744', type: 'icon', name: '统计图' },
      { data: 'icon-jinrong_tixing', fontContent: 'e743', type: 'icon', name: '提醒' },
      { data: 'icon-jinrong_chuangxinchanpin', fontContent: 'e742', type: 'icon', name: '创新产品' },
      { data: 'icon-jinrong_wode', fontContent: 'e741', type: 'icon', name: '我的' },
      { data: 'icon-jinrong_dengji-A', fontContent: 'e740', type: 'icon', name: '等级-A' },
      { data: 'icon-jinrong_dengji-D', fontContent: 'e73f', type: 'icon', name: '等级-D' },
      { data: 'icon-jinrong_dengji-B', fontContent: 'e73e', type: 'icon', name: '等级-B' },
      { data: 'icon-jinrong_dengji-C', fontContent: 'e72d', type: 'icon', name: '等级-C' },
      { data: 'icon-jinrong_qian', fontContent: 'e620', type: 'icon', name: '钱 金融 支付' },
      { data: 'icon-jinrong_jinrongxiaozhan', fontContent: 'e603', type: 'icon', name: '京东金融小图标' },
      { data: 'icon-jinrong_jinrong-', fontContent: 'e927', type: 'icon', name: '金融-53' },
      { data: 'icon-jinrong_jinrong', fontContent: 'e698', type: 'icon', name: '金融' },
      { data: 'icon-jinrong_nongcunjinrongba', fontContent: 'e606', type: 'icon', name: '农村金融吧' },
      { data: 'icon-jinrong_16', fontContent: 'e63a', type: 'icon', name: '金融' },
      { data: 'icon-jinrong_19', fontContent: 'e6be', type: 'icon', name: '金融' },
    ],
    name: '金融',
  },
  'icon-canyin': {
    items: [
      { data: 'icon-canyin_daochacanyin', fontContent: 'e73d', type: 'icon', name: '刀叉餐饮' },
      { data: 'icon-canyin_canyin8', fontContent: 'e940', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyinxitong-6', fontContent: 'e73c', type: 'icon', name: '餐饮系统-17' },
      { data: 'icon-canyin_canyinxitong-5', fontContent: 'e73b', type: 'icon', name: '餐饮系统-12' },
      { data: 'icon-canyin_canyinxitong-4', fontContent: 'e73a', type: 'icon', name: '餐饮系统-11' },
      { data: 'icon-canyin_canyinxitong-3', fontContent: 'e739', type: 'icon', name: '餐饮系统-13' },
      { data: 'icon-canyin_canyinxitong-2', fontContent: 'e738', type: 'icon', name: '餐饮系统-07' },
      { data: 'icon-canyin_canyinxitong-1', fontContent: 'e737', type: 'icon', name: '餐饮系统-02' },
      { data: 'icon-canyin_canyinxitong-', fontContent: 'e736', type: 'icon', name: '餐饮系统-04' },
      { data: 'icon-canyin_canyin7', fontContent: 'e735', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_huoguo', fontContent: 'e734', type: 'icon', name: '餐饮图标' },
      { data: 'icon-canyin_canyin6', fontContent: 'e733', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyintuancan', fontContent: 'e732', type: 'icon', name: '餐饮团餐' },
      { data: 'icon-canyin_canyin5', fontContent: 'e731', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_icon-', fontContent: 'e730', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyin4', fontContent: 'e8a4', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyin3', fontContent: 'e72f', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyin2', fontContent: 'e72e', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_canyin', fontContent: 'e72c', type: 'icon', name: '餐饮' },
      { data: 'icon-canyin_yingyuanxinxicanyin', fontContent: 'e72b', type: 'icon', name: '影院信息-餐饮' },
    ],
    name: '餐饮',
  },
  'icon-duomeiti': {
    items: [
      { data: 'icon-duomeiti_duomeiti', fontContent: 'e72a', type: 'icon', name: '多媒体' },
      { data: 'icon-duomeiti_meitiwenjian', fontContent: 'e729', type: 'icon', name: '多媒体' },
      { data: 'icon-duomeiti_938caidan_duomeiti', fontContent: 'e728', type: 'icon', name: '938菜单_多媒体' },
      { data: 'icon-duomeiti_shoucang-', fontContent: 'e727', type: 'icon', name: '收藏' },
      { data: 'icon-duomeiti_zhuanji-', fontContent: 'e726', type: 'icon', name: '专辑' },
      { data: 'icon-duomeiti_biaoqian-', fontContent: 'e725', type: 'icon', name: '标签' },
      { data: 'icon-duomeiti_dianshiju-', fontContent: 'e724', type: 'icon', name: '电视剧' },
      { data: 'icon-duomeiti_dianying-', fontContent: 'e71e', type: 'icon', name: '电影' },
      { data: 'icon-duomeiti_yinliang-', fontContent: 'e719', type: 'icon', name: '音量' },
      { data: 'icon-duomeiti_yuefu-', fontContent: 'e718', type: 'icon', name: '乐符' },
      { data: 'icon-duomeiti_maikefeng-', fontContent: 'e717', type: 'icon', name: '麦克风' },
      { data: 'icon-duomeiti_kuoyinqi-', fontContent: 'e716', type: 'icon', name: '扩音器' },
      { data: 'icon-duomeiti_zanting-1', fontContent: 'e624', type: 'icon', name: '暂停-02' },
      { data: 'icon-duomeiti_yinleku', fontContent: 'e623', type: 'icon', name: '音乐库' },
      { data: 'icon-duomeiti_zanting-', fontContent: 'e621', type: 'icon', name: '暂停' },
      { data: 'icon-duomeiti_bofangliebiao', fontContent: 'e61e', type: 'icon', name: '播放列表' },
      { data: 'icon-duomeiti_kuaijin-', fontContent: 'e61d', type: 'icon', name: '快进' },
      { data: 'icon-duomeiti_bofang-', fontContent: 'e61c', type: 'icon', name: '播放' },
      { data: 'icon-duomeiti_hualang', fontContent: 'e61b', type: 'icon', name: '画廊' },
      { data: 'icon-duomeiti_meitiku', fontContent: 'e61a', type: 'icon', name: '媒体库' },
      { data: 'icon-duomeiti_tupian', fontContent: 'e619', type: 'icon', name: '图片' },
      { data: 'icon-duomeiti_yinle', fontContent: 'e618', type: 'icon', name: '音乐' },
      { data: 'icon-duomeiti_xiangji', fontContent: 'e614', type: 'icon', name: '相机' },
    ],
    name: '多媒体',
  },
  'icon-yiliao': {
    items: [
      { data: 'icon-yiliao_yiliaohangyedeICON-6', fontContent: 'e715', type: 'icon', name: '处方药' },
      { data: 'icon-yiliao_yiliaohangyedeICON-5', fontContent: 'e714', type: 'icon', name: '骑车' },
      { data: 'icon-yiliao_yiliaohangyedeICON-4', fontContent: 'e713', type: 'icon', name: '医院' },
      { data: 'icon-yiliao_yiliaohangyedeICON-3', fontContent: 'e712', type: 'icon', name: '提示信息' },
      { data: 'icon-yiliao_yiliaohangyedeICON-2', fontContent: 'e617', type: 'icon', name: '药品' },
      { data: 'icon-yiliao_yiliaohangyedeICON-1', fontContent: 'e616', type: 'icon', name: '预约日期' },
      { data: 'icon-yiliao_yiyuanguahao', fontContent: 'e615', type: 'icon', name: '医院挂号' },
      { data: 'icon-yiliao_guahao', fontContent: 'e613', type: 'icon', name: '挂号' },
      { data: 'icon-yiliao_jiankangdangan', fontContent: 'e612', type: 'icon', name: '健康档案' },
      { data: 'icon-yiliao_yixuekepu', fontContent: 'e611', type: 'icon', name: '医学科普' },
      { data: 'icon-yiliao_zhengzhuangzicha', fontContent: 'e60f', type: 'icon', name: '症状自查' },
      { data: 'icon-yiliao_mingyizhuanjia', fontContent: 'e60e', type: 'icon', name: '名医专家' },
      { data: 'icon-yiliao_yiliaohangyedeICON-', fontContent: 'e60b', type: 'icon', name: '专项检查' },
      { data: 'icon-yiliao_tubiaozhizuomoban-lly', fontContent: 'e60a', type: 'icon', name: '预约医生' },
      { data: 'icon-yiliao_xiaofeijilu', fontContent: 'e711', type: 'icon', name: '消费记录' },
      { data: 'icon-yiliao_taocanjilu', fontContent: 'e710', type: 'icon', name: '套餐记录' },
      { data: 'icon-yiliao_jiuzhenjilu', fontContent: 'e70f', type: 'icon', name: '就诊记录' },
      { data: 'icon-yiliao_wenjuan', fontContent: 'e70e', type: 'icon', name: '问卷' },
      { data: 'icon-yiliao_jiancha', fontContent: 'e70d', type: 'icon', name: '检查' },
      { data: 'icon-yiliao_yuyuexinxi', fontContent: 'e70a', type: 'icon', name: '预约信息' },
      { data: 'icon-yiliao_feiyong', fontContent: 'e709', type: 'icon', name: '费用' },
      { data: 'icon-yiliao_zhishi', fontContent: 'e708', type: 'icon', name: '知识' },
      { data: 'icon-yiliao_tousu', fontContent: 'e707', type: 'icon', name: '投诉' },
      { data: 'icon-yiliao_kefu', fontContent: 'e706', type: 'icon', name: '客服' },
      { data: 'icon-yiliao_wodexuanzhong', fontContent: 'e6f6', type: 'icon', name: '我的选中' },
      { data: 'icon-yiliao_wode', fontContent: 'e6e9', type: 'icon', name: '我的' },
      { data: 'icon-yiliao_faxianxuanzhong', fontContent: 'e6c2', type: 'icon', name: '发现选中' },
      { data: 'icon-yiliao_faxian', fontContent: 'e6bb', type: 'icon', name: '发现' },
      { data: 'icon-yiliao_yuyuexuanzhong', fontContent: 'e6b2', type: 'icon', name: '预约选中' },
      { data: 'icon-yiliao_yuyue', fontContent: 'e6b1', type: 'icon', name: '预约' },
      { data: 'icon-yiliao_zixunxuanzhong', fontContent: 'e6a9', type: 'icon', name: '咨询选中' },
      { data: 'icon-yiliao_zixun', fontContent: 'e69e', type: 'icon', name: '咨询' },
    ],
    name: '医疗',
  },
  'icon-xiaochengxu': {
    items: [
      { data: 'icon-xiaochengxu_QQ', fontContent: 'e723', type: 'icon', name: 'QQ' },
      { data: 'icon-xiaochengxu_xiaochengxu', fontContent: 'e722', type: 'icon', name: '小程序' },
      { data: 'icon-xiaochengxu_dianhua1', fontContent: 'e721', type: 'icon', name: '电话' },
      { data: 'icon-xiaochengxu_zhifubao', fontContent: 'e720', type: 'icon', name: '支付宝' },
      { data: 'icon-xiaochengxu_weixinzhifu1', fontContent: 'e71f', type: 'icon', name: '19微信支付' },
      { data: 'icon-xiaochengxu_weixin1', fontContent: 'e71d', type: 'icon', name: '微信' },
      { data: 'icon-xiaochengxu_guanbi1', fontContent: 'e71c', type: 'icon', name: '关闭' },
      { data: 'icon-xiaochengxu_daishouhuo', fontContent: 'e71b', type: 'icon', name: '待收货' },
      { data: 'icon-xiaochengxu_daifukuan', fontContent: 'e71a', type: 'icon', name: '待付款' },
      { data: 'icon-xiaochengxu_tubiaozhizuomoEban', fontContent: 'e70c', type: 'icon', name: '购买' },
      { data: 'icon-xiaochengxu_tubiaozhizuomoban', fontContent: 'e70b', type: 'icon', name: '出售' },
      { data: 'icon-xiaochengxu_gengduo', fontContent: 'e705', type: 'icon', name: '更多2' },
      { data: 'icon-xiaochengxu_fenlei1', fontContent: 'e704', type: 'icon', name: '分类' },
      { data: 'icon-xiaochengxu_faxian', fontContent: 'e703', type: 'icon', name: '发现' },
      { data: 'icon-xiaochengxu_yiwen', fontContent: 'e702', type: 'icon', name: '疑问' },
      { data: 'icon-xiaochengxu_guanyuwomen', fontContent: 'e701', type: 'icon', name: '关于我们' },
      { data: 'icon-xiaochengxu_mimasuo', fontContent: 'e700', type: 'icon', name: '密码 锁' },
      { data: 'icon-xiaochengxu_shouji', fontContent: 'e6ff', type: 'icon', name: '手机' },
      { data: 'icon-xiaochengxu_dizhi', fontContent: 'e6fe', type: 'icon', name: '地址' },
      { data: 'icon-xiaochengxu_zhaoxiangji', fontContent: 'e6fd', type: 'icon', name: '照相机 发现' },
      { data: 'icon-xiaochengxu_kefu', fontContent: 'e6fc', type: 'icon', name: '客服' },
      { data: 'icon-xiaochengxu_zuji', fontContent: 'e6fb', type: 'icon', name: '足迹' },
      { data: 'icon-xiaochengxu_pingjia', fontContent: 'e6fa', type: 'icon', name: '评价' },
      { data: 'icon-xiaochengxu_dianzan', fontContent: 'e6f9', type: 'icon', name: '点赞' },
      { data: 'icon-xiaochengxu_biaoqian', fontContent: 'e6f8', type: 'icon', name: '标签' },
      { data: 'icon-xiaochengxu_shouye1', fontContent: 'e6f7', type: 'icon', name: '首页' },
      { data: 'icon-xiaochengxu_gouwuche', fontContent: 'e6f5', type: 'icon', name: '购物车' },
      { data: 'icon-xiaochengxu_renminbi', fontContent: 'e6f4', type: 'icon', name: '人民币1' },
      { data: 'icon-xiaochengxu_yinliang1', fontContent: 'e6f3', type: 'icon', name: '音量02' },
      { data: 'icon-xiaochengxu_shijianfenlei', fontContent: 'e6f2', type: 'icon', name: '时间分类' },
      { data: 'icon-xiaochengxu_gengxinshijian', fontContent: 'e6f1', type: 'icon', name: '更新时间' },
      { data: 'icon-xiaochengxu_yinliang', fontContent: 'e6f0', type: 'icon', name: '音量01' },
      { data: 'icon-xiaochengxu_huiyuandefuben', fontContent: 'e6ef', type: 'icon', name: '会员的副本' },
      { data: 'icon-xiaochengxu_luyin', fontContent: 'e6ee', type: 'icon', name: '录音' },
      { data: 'icon-xiaochengxu_riqi', fontContent: 'e6ed', type: 'icon', name: '日期' },
      { data: 'icon-xiaochengxu_baiban', fontContent: 'e6ec', type: 'icon', name: '白板' },
      { data: 'icon-xiaochengxu_wode', fontContent: 'e6eb', type: 'icon', name: '我的' },
      { data: 'icon-xiaochengxu_shijianxuanzeqi', fontContent: 'e6ea', type: 'icon', name: '时间选择器' },
      { data: 'icon-xiaochengxu_caozuo-dianhua', fontContent: 'e6e8', type: 'icon', name: '操作-电话' },
      { data: 'icon-xiaochengxu_xiaolian', fontContent: 'e6e7', type: 'icon', name: '笑脸' },
      { data: 'icon-xiaochengxu_jifenshangcheng', fontContent: 'e6e6', type: 'icon', name: '积分商城' },
      { data: 'icon-xiaochengxu_qiaquan', fontContent: 'e6e5', type: 'icon', name: '卡券' },
      { data: 'icon-xiaochengxu_dianpu', fontContent: 'e6e4', type: 'icon', name: '店铺' },
      { data: 'icon-xiaochengxu_bofang', fontContent: 'e6e3', type: 'icon', name: '播放' },
      { data: 'icon-xiaochengxu_fenxiang', fontContent: 'e6e2', type: 'icon', name: '分享 ' },
      { data: 'icon-xiaochengxu_zanting', fontContent: 'e6e1', type: 'icon', name: '暂停' },
      { data: 'icon-xiaochengxu_yonghuguanli', fontContent: 'e6e0', type: 'icon', name: '用户管理' },
      { data: 'icon-xiaochengxu_yiguanzhu', fontContent: 'e6df', type: 'icon', name: '已关注' },
      { data: 'icon-xiaochengxu_shouye', fontContent: 'e6de', type: 'icon', name: '首页' },
      { data: 'icon-xiaochengxu_renwu-zengjia', fontContent: 'e6dd', type: 'icon', name: '人物-增加' },
      { data: 'icon-xiaochengxu_zengjia2', fontContent: 'e6dc', type: 'icon', name: '增加' },
      { data: 'icon-xiaochengxu_zengjia1', fontContent: 'e6db', type: 'icon', name: '增加 (2)' },
      { data: 'icon-xiaochengxu_guanbi', fontContent: 'e6d9', type: 'icon', name: '关闭' },
      { data: 'icon-xiaochengxu_jianshao1', fontContent: 'e6d8', type: 'icon', name: '减少 (3)' },
      { data: 'icon-xiaochengxu_jianshao', fontContent: 'e6d7', type: 'icon', name: '减少 (2)' },
      { data: 'icon-xiaochengxu_xuanze', fontContent: 'e6d6', type: 'icon', name: '选择 ' },
      { data: 'icon-xiaochengxu_xuanze-yixuan', fontContent: 'e6d5', type: 'icon', name: '选择-已选' },
      { data: 'icon-xiaochengxu_xihuan1', fontContent: 'e6d4', type: 'icon', name: '喜欢 ' },
      { data: 'icon-xiaochengxu_xihuan', fontContent: 'e6d3', type: 'icon', name: '喜欢' },
      { data: 'icon-xiaochengxu_shenhe', fontContent: 'e6d2', type: 'icon', name: '审核' },
      { data: 'icon-xiaochengxu_pifu', fontContent: 'e6d1', type: 'icon', name: '皮肤' },
      { data: 'icon-xiaochengxu_liulan', fontContent: 'e6d0', type: 'icon', name: '浏览' },
      { data: 'icon-xiaochengxu_fuhao-biaoqian', fontContent: 'e6cf', type: 'icon', name: '标签' },
      { data: 'icon-xiaochengxu_kehu', fontContent: 'e6ce', type: 'icon', name: '客户' },
      { data: 'icon-xiaochengxu_qianbao', fontContent: 'e6cd', type: 'icon', name: '钱包' },
      { data: 'icon-xiaochengxu_lianxiren', fontContent: 'e6cc', type: 'icon', name: '联系人' },
      { data: 'icon-xiaochengxu_fanhui1', fontContent: 'e6cb', type: 'icon', name: '返回' },
      { data: 'icon-xiaochengxu_fuwuqi', fontContent: 'e6ca', type: 'icon', name: '服务器' },
      { data: 'icon-xiaochengxu_fabu', fontContent: 'e6c9', type: 'icon', name: '发布' },
      { data: 'icon-xiaochengxu_erweima', fontContent: 'e6c8', type: 'icon', name: '二维码' },
      { data: 'icon-xiaochengxu_caozuo-shangchuan-download', fontContent: 'e6c7', type: 'icon', name: '下载' },
      { data: 'icon-xiaochengxu_caozuo-shangchuan-upload', fontContent: 'e6c6', type: 'icon', name: '上传' },
      { data: 'icon-xiaochengxu_huo', fontContent: 'e6c5', type: 'icon', name: '火' },
      { data: 'icon-xiaochengxu_bingzhuangtu', fontContent: 'e6c4', type: 'icon', name: '饼状图 分类' },
      { data: 'icon-xiaochengxu_shujishuaxin', fontContent: 'e6c3', type: 'icon', name: '书籍刷新' },
      { data: 'icon-xiaochengxu_nv', fontContent: 'e6c1', type: 'icon', name: '女' },
      { data: 'icon-xiaochengxu_xiangji', fontContent: 'e6c0', type: 'icon', name: '相机' },
      { data: 'icon-xiaochengxu_shuji', fontContent: 'e6bf', type: 'icon', name: '书籍01' },
      { data: 'icon-xiaochengxu_dianying', fontContent: 'e6bd', type: 'icon', name: '电影' },
      { data: 'icon-xiaochengxu_tishi', fontContent: 'e6bc', type: 'icon', name: '提示' },
      { data: 'icon-xiaochengxu_zhiyin', fontContent: 'e6ba', type: 'icon', name: '指引' },
      { data: 'icon-xiaochengxu_yinle', fontContent: 'e6b9', type: 'icon', name: '音乐' },
      { data: 'icon-xiaochengxu_nan', fontContent: 'e6b8', type: 'icon', name: '男' },
      { data: 'icon-xiaochengxu_zhiye', fontContent: 'e6b7', type: 'icon', name: '职业' },
      { data: 'icon-xiaochengxu_yejibaobiao', fontContent: 'e6b6', type: 'icon', name: '业绩报表 交易记录' },
      { data: 'icon-xiaochengxu_luxiangji', fontContent: 'e6b5', type: 'icon', name: '录像机' },
      { data: 'icon-xiaochengxu_shuaxin', fontContent: 'e6b4', type: 'icon', name: '刷新' },
      { data: 'icon-xiaochengxu_shafa', fontContent: 'e6b3', type: 'icon', name: '沙发' },
      { data: 'icon-xiaochengxu_shenpi', fontContent: 'e6b0', type: 'icon', name: '审批' },
      { data: 'icon-xiaochengxu_VIP', fontContent: 'e6af', type: 'icon', name: 'VIP' },
      { data: 'icon-xiaochengxu_zuguanli', fontContent: 'e6ae', type: 'icon', name: '组管理' },
      { data: 'icon-xiaochengxu_ziyuanguanli', fontContent: 'e6ad', type: 'icon', name: '资源管理' },
      { data: 'icon-xiaochengxu_yinhangqia', fontContent: 'e6ac', type: 'icon', name: '银行卡' },
      { data: 'icon-xiaochengxu_hanglixiang', fontContent: 'e6ab', type: 'icon', name: '行李箱' },
      { data: 'icon-xiaochengxu_bianji', fontContent: 'e6aa', type: 'icon', name: '编辑 (1)' },
      { data: 'icon-xiaochengxu_ziliao', fontContent: 'e6a8', type: 'icon', name: '资料' },
      { data: 'icon-xiaochengxu_xiangxia', fontContent: 'e6a7', type: 'icon', name: '向下' },
      { data: 'icon-xiaochengxu_xiangshang', fontContent: 'e6a6', type: 'icon', name: '向上' },
      { data: 'icon-xiaochengxu_xiangzuo', fontContent: 'e6a5', type: 'icon', name: '向左' },
      { data: 'icon-xiaochengxu_xiangyou', fontContent: 'e6a4', type: 'icon', name: '向右' },
      { data: 'icon-xiaochengxu_gouwu1', fontContent: 'e6a3', type: 'icon', name: '购物' },
      { data: 'icon-xiaochengxu_gouwu', fontContent: 'e6a2', type: 'icon', name: '购物' },
      { data: 'icon-xiaochengxu_weixinzhifu', fontContent: 'e6a1', type: 'icon', name: '微信支付' },
      { data: 'icon-xiaochengxu_renminbicaiwuzhifu', fontContent: 'e6a0', type: 'icon', name: '余额支付' },
      { data: 'icon-xiaochengxu_shijian', fontContent: 'e69f', type: 'icon', name: '时间  日期' },
      { data: 'icon-xiaochengxu_hangyepaihang', fontContent: 'e69d', type: 'icon', name: '行业排行 奖杯' },
      { data: 'icon-xiaochengxu_weixin', fontContent: 'e69c', type: 'icon', name: '微信' },
      { data: 'icon-xiaochengxu_dingdan', fontContent: 'e69b', type: 'icon', name: '订单' },
      { data: 'icon-xiaochengxu_xiaoxi1', fontContent: 'e69a', type: 'icon', name: '消息' },
      { data: 'icon-xiaochengxu_xiaoxi', fontContent: 'e699', type: 'icon', name: '消息 ' },
      { data: 'icon-xiaochengxu_shoucang', fontContent: 'e675', type: 'icon', name: '收藏' },
      { data: 'icon-xiaochengxu_zhifubaoqianbao', fontContent: 'e622', type: 'icon', name: '支付宝钱包' },
      { data: 'icon-xiaochengxu_licaishouyi', fontContent: 'e61f', type: 'icon', name: '理财收益' },
      { data: 'icon-xiaochengxu_fanhui', fontContent: 'e60d', type: 'icon', name: '返回' },
      { data: 'icon-xiaochengxu_jinru', fontContent: 'e60c', type: 'icon', name: '进入' },
      { data: 'icon-xiaochengxu_shezhi', fontContent: 'e609', type: 'icon', name: '设置' },
      { data: 'icon-xiaochengxu_pinglun', fontContent: 'e608', type: 'icon', name: '评论' },
      { data: 'icon-xiaochengxu_sousuo', fontContent: 'e607', type: 'icon', name: '搜索' },
      { data: 'icon-xiaochengxu_shanchu', fontContent: 'e605', type: 'icon', name: '删除' },
      { data: 'icon-xiaochengxu_saoyisao', fontContent: 'e604', type: 'icon', name: '扫一扫' },
    ],
    name: '小程序',
  },
  'icon-tongyong': {
    items: [
      { data: 'icon-tongyong_zengjia', fontContent: 'e6da', type: 'icon', name: '增加 (1)' },
      { data: 'icon-tongyong_folder-line-copy', fontContent: 'e697', type: 'icon', name: '文件夹' },
      { data: 'icon-tongyong_preview-line', fontContent: 'e696', type: 'icon', name: '预览' },
      { data: 'icon-tongyong_add-line1', fontContent: 'e695', type: 'icon', name: '添加' },
      { data: 'icon-tongyong_add-circle-s', fontContent: 'e694', type: 'icon', name: '添加' },
      { data: 'icon-tongyong_download', fontContent: 'e693', type: 'icon', name: '下载' },
      { data: 'icon-tongyong_shouqi-copy', fontContent: 'e692', type: 'icon', name: '收起' },
      { data: 'icon-tongyong_email-s', fontContent: 'e691', type: 'icon', name: '邮件-实色' },
      { data: 'icon-tongyong_email-line', fontContent: 'e690', type: 'icon', name: '邮件' },
      { data: 'icon-tongyong_essential', fontContent: 'e68f', type: 'icon', name: '必填' },
      { data: 'icon-tongyong_flow-others', fontContent: 'e68e', type: 'icon', name: '流程-其他投递机会及归属' },
      { data: 'icon-tongyong_flow-Mark', fontContent: 'e68d', type: 'icon', name: '流程-备注' },
      { data: 'icon-tongyong_flow-owner', fontContent: 'e68c', type: 'icon', name: '流程-简历操作及归属' },
      { data: 'icon-tongyong_flow-entry', fontContent: 'e68b', type: 'icon', name: '流程-入职管理' },
      { data: 'icon-tongyong_flow-log', fontContent: 'e68a', type: 'icon', name: '流程-流程日志' },
      { data: 'icon-tongyong_flow-determine', fontContent: 'e689', type: 'icon', name: '流程-测评管理' },
      { data: 'icon-tongyong_flow-offer', fontContent: 'e688', type: 'icon', name: '流程-offer管理' },
      { data: 'icon-tongyong_flow-resume', fontContent: 'e687', type: 'icon', name: '流程-简历' },
      { data: 'icon-tongyong_flow-interview', fontContent: 'e686', type: 'icon', name: '流程-面试管理' },
      { data: 'icon-tongyong_fill', fontContent: 'e685', type: 'icon', name: '填写' },
      { data: 'icon-tongyong_haier', fontContent: 'e684', type: 'icon', name: '海尔' },
      { data: 'icon-tongyong_n', fontContent: 'e683', type: 'icon', name: 'n' },
      { data: 'icon-tongyong_list2', fontContent: 'e682', type: 'icon', name: '菜单栏' },
      { data: 'icon-tongyong_list', fontContent: 'e681', type: 'icon', name: '列表' },
      { data: 'icon-tongyong_more', fontContent: 'e680', type: 'icon', name: '更多' },
      { data: 'icon-tongyong_switch', fontContent: 'e67f', type: 'icon', name: '切换' },
      { data: 'icon-tongyong_lightning', fontContent: 'e67e', type: 'icon', name: '闪聘' },
      { data: 'icon-tongyong_loc-line', fontContent: 'e67d', type: 'icon', name: '定位' },
      { data: 'icon-tongyong_loc-s', fontContent: 'e67c', type: 'icon', name: '定位-实色' },
      { data: 'icon-tongyong_menu-s', fontContent: 'e67b', type: 'icon', name: '菜单-实色' },
      { data: 'icon-tongyong_menu-line', fontContent: 'e67a', type: 'icon', name: '菜单' },
      { data: 'icon-tongyong_send-line', fontContent: 'e679', type: 'icon', name: '发送' },
      { data: 'icon-tongyong_send-s', fontContent: 'e678', type: 'icon', name: '发送-实色' },
      { data: 'icon-tongyong_talk-s', fontContent: 'e677', type: 'icon', name: '对话-实色' },
      { data: 'icon-tongyong_talk-line', fontContent: 'e676', type: 'icon', name: '对话' },
      { data: 'icon-tongyong_doc-s', fontContent: 'e674', type: 'icon', name: '文件-实色' },
      { data: 'icon-tongyong_check-s', fontContent: 'e673', type: 'icon', name: '查看-实色' },
      { data: 'icon-tongyong_check-line', fontContent: 'e672', type: 'icon', name: '查看' },
      { data: 'icon-tongyong_remind-s', fontContent: 'e671', type: 'icon', name: '提示-灯泡-实色' },
      { data: 'icon-tongyong_remind-line', fontContent: 'e670', type: 'icon', name: '提示-灯泡' },
      { data: 'icon-tongyong_tel-s', fontContent: 'e66f', type: 'icon', name: '电话-实色' },
      { data: 'icon-tongyong_tel-line', fontContent: 'e66e', type: 'icon', name: '电话' },
      { data: 'icon-tongyong_resume-line', fontContent: 'e66d', type: 'icon', name: '简历' },
      { data: 'icon-tongyong_resume-s', fontContent: 'e66c', type: 'icon', name: '简历-实色' },
      { data: 'icon-tongyong_bonus-line', fontContent: 'e66b', type: 'icon', name: '积分' },
      { data: 'icon-tongyong_bonus-s', fontContent: 'e66a', type: 'icon', name: '积分-实色' },
      { data: 'icon-tongyong_set-s', fontContent: 'e669', type: 'icon', name: '设置-实色' },
      { data: 'icon-tongyong_set-line', fontContent: 'e668', type: 'icon', name: '设置' },
      { data: 'icon-tongyong_save-s', fontContent: 'e667', type: 'icon', name: '保存-实色' },
      { data: 'icon-tongyong_save-line', fontContent: 'e666', type: 'icon', name: '保存' },
      { data: 'icon-tongyong_pic-s', fontContent: 'e665', type: 'icon', name: '图片-实色' },
      { data: 'icon-tongyong_pic-line', fontContent: 'e664', type: 'icon', name: '图片' },
      { data: 'icon-tongyong_camera-s', fontContent: 'e663', type: 'icon', name: '相机-实色' },
      { data: 'icon-tongyong_camera-line', fontContent: 'e662', type: 'icon', name: '相机' },
      { data: 'icon-tongyong_voice-line', fontContent: 'e661', type: 'icon', name: '语音' },
      { data: 'icon-tongyong_voice-s', fontContent: 'e660', type: 'icon', name: '语音-实色' },
      { data: 'icon-tongyong_activity-line', fontContent: 'e65f', type: 'icon', name: '活动' },
      { data: 'icon-tongyong_activity-s', fontContent: 'e65e', type: 'icon', name: '活动-实色' },
      { data: 'icon-tongyong_note', fontContent: 'e65d', type: 'icon', name: '注释' },
      { data: 'icon-tongyong_scan-line', fontContent: 'e65c', type: 'icon', name: '扫描' },
      { data: 'icon-tongyong_refresh-line', fontContent: 'e65b', type: 'icon', name: '刷新' },
      { data: 'icon-tongyong_link-line', fontContent: 'e65a', type: 'icon', name: '链接' },
      { data: 'icon-tongyong_gender', fontContent: 'e659', type: 'icon', name: '性别' },
      { data: 'icon-tongyong_edit-line', fontContent: 'e658', type: 'icon', name: '编辑' },
      { data: 'icon-tongyong_flow-line', fontContent: 'e657', type: 'icon', name: '流程' },
      { data: 'icon-tongyong_delete', fontContent: 'e656', type: 'icon', name: '删除' },
      { data: 'icon-tongyong_calendar-line', fontContent: 'e655', type: 'icon', name: '日历' },
      { data: 'icon-tongyong_search-line', fontContent: 'e654', type: 'icon', name: '搜索' },
      { data: 'icon-tongyong_spread-line', fontContent: 'e653', type: 'icon', name: '展开' },
      { data: 'icon-tongyong_edu-s', fontContent: 'e652', type: 'icon', name: '学历-实色' },
      { data: 'icon-tongyong_edu-line', fontContent: 'e651', type: 'icon', name: '学历' },
      { data: 'icon-tongyong_folder-line', fontContent: 'e650', type: 'icon', name: '文件夹' },
      { data: 'icon-tongyong_folder-s', fontContent: 'e64f', type: 'icon', name: '文件夹-实色' },
      { data: 'icon-tongyong_work-line', fontContent: 'e64e', type: 'icon', name: '职能' },
      { data: 'icon-tongyong_work-s', fontContent: 'e64d', type: 'icon', name: '职能-实色' },
      { data: 'icon-tongyong_nice-line', fontContent: 'e64c', type: 'icon', name: '赞' },
      { data: 'icon-tongyong_nice', fontContent: 'e64b', type: 'icon', name: '赞-实色' },
      { data: 'icon-tongyong_share-line', fontContent: 'e64a', type: 'icon', name: '分享' },
      { data: 'icon-tongyong_share-s', fontContent: 'e649', type: 'icon', name: '分享-实色' },
      { data: 'icon-tongyong_lock-s', fontContent: 'e648', type: 'icon', name: '锁定-实色' },
      { data: 'icon-tongyong_lock-line', fontContent: 'e647', type: 'icon', name: '锁定' },
      { data: 'icon-tongyong_ulock-line', fontContent: 'e646', type: 'icon', name: '解锁' },
      { data: 'icon-tongyong_delete-s', fontContent: 'e645', type: 'icon', name: '删除' },
      { data: 'icon-tongyong_add-line', fontContent: 'e644', type: 'icon', name: '添加' },
      { data: 'icon-tongyong_plus-line', fontContent: 'e643', type: 'icon', name: '加号' },
      { data: 'icon-tongyong_user-line', fontContent: 'e642', type: 'icon', name: '用户' },
      { data: 'icon-tongyong_user-s', fontContent: 'e641', type: 'icon', name: '用户-实色' },
      { data: 'icon-tongyong_like-s', fontContent: 'e640', type: 'icon', name: '心-实色' },
      { data: 'icon-tongyong_like-line', fontContent: 'e63f', type: 'icon', name: '心' },
      { data: 'icon-tongyong_favorite-s', fontContent: 'e63e', type: 'icon', name: '收藏-实色' },
      { data: 'icon-tongyong_favorite-line', fontContent: 'e63d', type: 'icon', name: '收藏' },
      { data: 'icon-tongyong_home-s', fontContent: 'e63c', type: 'icon', name: '主页-实色' },
      { data: 'icon-tongyong_home-line', fontContent: 'e63b', type: 'icon', name: '主页' },
      { data: 'icon-tongyong_question-s', fontContent: 'e639', type: 'icon', name: '疑问-实色' },
      { data: 'icon-tongyong_question-line', fontContent: 'e638', type: 'icon', name: '疑问' },
      { data: 'icon-tongyong_warn-s', fontContent: 'e637', type: 'icon', name: '注意-实色' },
      { data: 'icon-tongyong_warn-line', fontContent: 'e636', type: 'icon', name: '注意' },
      { data: 'icon-tongyong_close-s', fontContent: 'e635', type: 'icon', name: '关闭-圆形实色' },
      { data: 'icon-tongyong_close-line', fontContent: 'e634', type: 'icon', name: '关闭' },
      { data: 'icon-tongyong_close-line-c', fontContent: 'e633', type: 'icon', name: '关闭-圆' },
      { data: 'icon-tongyong_confirm-line', fontContent: 'e632', type: 'icon', name: '对勾' },
      { data: 'icon-tongyong_select-line', fontContent: 'e631', type: 'icon', name: '勾选-圆' },
      { data: 'icon-tongyong_select-s', fontContent: 'e630', type: 'icon', name: '勾选-圆形实色' },
      { data: 'icon-tongyong_choose-s', fontContent: 'e62f', type: 'icon', name: '勾选-实色' },
      { data: 'icon-tongyong_choose-line', fontContent: 'e62e', type: 'icon', name: '勾选' },
      { data: 'icon-tongyong_below-s', fontContent: 'e62d', type: 'icon', name: '下-三角' },
      { data: 'icon-tongyong_left-s', fontContent: 'e62c', type: 'icon', name: '左-三角' },
      { data: 'icon-tongyong_top-s', fontContent: 'e62b', type: 'icon', name: '上-三角' },
      { data: 'icon-tongyong_right-s', fontContent: 'e62a', type: 'icon', name: '右-三角' },
      { data: 'icon-tongyong_below-line', fontContent: 'e629', type: 'icon', name: '下' },
      { data: 'icon-tongyong_right-line', fontContent: 'e628', type: 'icon', name: '右' },
      { data: 'icon-tongyong_left-line', fontContent: 'e626', type: 'icon', name: '左' },
      { data: 'icon-tongyong_top-line', fontContent: 'e625', type: 'icon', name: '上' },
    ],
    name: '通用',
  },
  'icon-fangxiang': {
    items: [
      { data: 'icon-fangxiang_xiaoxifangxiang', fontContent: 'e627', type: 'icon', name: '消息方向' },
      { data: 'icon-fangxiang_fangxiang4', fontContent: 'e602', type: 'icon', name: '方向4' },
      { data: 'icon-fangxiang_fangxiang3', fontContent: 'e601', type: 'icon', name: '方向3' },
      { data: 'icon-fangxiang_fangxiang2', fontContent: 'e600', type: 'icon', name: '方向2' },
      { data: 'icon-fangxiang_ziyuan', fontContent: 'e610', type: 'icon', name: '资源 41' },
    ],
    name: '方向',
  },
};
